### ISSUE TITLE
Types issues in v4 ?

### ISSUE THREAD

**Issue by dperetti** [paulmillr/chokidar#1416]
**Describe the bug**

Just upgraded my project from v 3.6 to v4. Worked without hassle, but some type definitions seem to be broken in v4.

**Versions:**
 - Chokidar version 4.02
 - Typescript 5.7.3

**To Reproduce:**

```      
const watcher = chokidar.watch(watchedPaths, {
        persistent: true,
        useFsEvents: true, // 👈 Typescript Error: useFsEvents does not exist in type
        usePolling: false,
        ignoreInitial: true,
        disableGlobbing: true
      })
      //👇 TS2576: Property on does not exist on type FSWatcher. Did you mean to access the static member FSWatcher. on instead?
      .on('change', (f, stats) => {
              log.info(`File ${f} changed. root: (${sourceFullPath})`)
            })
```

**Comment by dperetti** [comment]
Ok just figured out it's related to https://github.com/paulmillr/chokidar/issues/1392 . But why was it closed?

**Comment by 43081j** [comment]
as per the last comment in that thread, that person's problem was because we hadn't published the type constraint yet

so unless you also haven't updated to latest 4.x, that issue is unrelated and has correctly been closed

`useFsEvents` isn't an option anymore, as we don't use fs events. i see there are some remnants of it in the readme, we should remove those.

if removing that doesn't help, let me know. it could be that you need to `npm up @types/node` but not sure why that'd be the case

**Comment by JoshuaHintze** [comment]
I'm seeing the same problem. 

		"chokidar": "^4.0.3",
		"@types/node": "20.11.20",
		"typescript": "^5.6.3",

```
		const watcher: FSWatcher = chokidar.watch(this.inboxPath, {
			persistent: true,
			ignoreInitial: false,
			ignored: (path, stats) => {
				if (stats && stats.isFile()) {
					return !path.endsWith('.json');
				}
				return false;
			}
		});
		
               // ERROR HERE: Property 'on' does not exist on type 'FSWatcher'. Did you mean to access the static member 'FSWatcher.on' instead?ts(2576)

		watcher.on('add', async (filePath) => { console.log('File added: ' + filePath); });
```

**Comment by 43081j** [comment]
Which doesn't make much sense since it always had an `on` method before and after the type changes

Can you tell us exactly which versions it installed? (`npm ls @types/node`)

And when you mouse over `watcher` or something in your editor, what is it?

If you jump to the definition of `FSWatcher` in your editor, what is the first line? (The class declaration)

**Comment by JoshuaHintze** [comment]
Here are some screen shots.

![Image](https://github.com/user-attachments/assets/3adbd4d0-5965-4ac4-bff6-4dbc58167e2c)

![Image](https://github.com/user-attachments/assets/799eb1c4-0c9f-4a17-9f04-caa855394df9)

When I go to definition I get this.

![Image](https://github.com/user-attachments/assets/9a39c2f7-fbfd-4bc0-aec8-cdf8e11fa24b)

![Image](https://github.com/user-attachments/assets/8029e617-7b88-4d2b-bf87-4c587399c6bb)


Using @types/node 20.11.20

FYI - and maybe this is the culprit. I'm using pnpm and not npm or yarn.

**Comment by dperetti** [comment]
> if removing that doesn't help, let me know. it could be that you need to `npm up @types/node` but not sure why that'd be the case

Thank you, indeed my @types/node was outdated! 🫢 

It's now working fine with @types/node 22.10.10 .

**Comment by 43081j** [comment]
Yep the same for you @JoshuaHintze , the version of `@types/node` you have is before they added a type parameter to `EventEmitter` it seems

If you update that, it'll probably work fine

**Comment by JoshuaHintze** [comment]
Thanks @43081j - I'm curious doesn't @types/node 22.X.X mean you are using node 22 LTS? If we are actually using Node 20.X.X wouldn't that be an issuse,

Or perhaps you are saying that they typedef maintainers missed a key piece that has always been in there? What is the min requirement for v4 chokidar?

**Comment by 43081j** [comment]
It's purely a types thing so it doesn't align to a version of node. Since node had event emitters (long ago), this was the correct type. At some point they fixed the types but that is nothing to do with any particular node support

**Comment by qkang07** [comment]
> > if removing that doesn't help, let me know. it could be that you need to `npm up @types/node` but not sure why that'd be the case
> 
> Thank you, indeed my @types/node was outdated! 🫢
> 
> It's now working fine with @types/node 22.10.10 .

hello everyone, I'm using @types/node@22.13.8 but it still not working.

**Comment by 43081j** [comment]
That seems unlikely. Is it possible you have more than one `@types/node`?

The node types certainly have strongly typed event emitters. So it would be strange if you're not seeing that

**Comment by JoshuaHintze** [comment]
Just for feedback, when I updated from @types/node@20X -> @types/node@22X it solved my issue.
